question_data = [
          {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
           "question": "In 'The Sims' series, the most members in a household you can have is 8.",
           "correct_answer": "True", "incorrect_answers": ["False"]},
          {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
           "question": "Arcade Fire&#039;s &#039;The Suburbs&#039; won the Album of the Year award in the 2011 Grammys."
           ,
           "correct_answer": "True", "incorrect_answers": ["False"]},
          {"category": "Entertainment: Video Games", "type": "boolean",
           "difficulty": "medium", "question": "Super Mario Bros. was released in 1990.",
           "correct_answer": "False", "incorrect_answers": ["True"]},
          {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
           "question": "Pac-Man was invented by the designer Toru Iwatani while he was eating pizza.",
           "correct_answer": "True", "incorrect_answers": ["False"]},
          {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
           "question": "The ultimate phrase used by Pharah from Overwatch is: &quot;Justice rains from above!&quot;",
           "correct_answer": "True", "incorrect_answers": ["False"]},
          {"category": "Vehicles", "type": "boolean", "difficulty": "easy",
           "question": "The full English name of the car manufacturer BMW is Bavarian Motor Works",
           "correct_answer": "True", "incorrect_answers": ["False"]},
          {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
           "question": "Pluto is a planet.", "correct_answer": "False",
           "incorrect_answers": ["True"]},
          {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
           "question": "&quot;HTML&quot; stands for Hypertext Markup Language.",
           "correct_answer": "True", "incorrect_answers": ["False"]},
          {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
           "question": "In Sonic the Hedgehog universe, Tails&#039; real name is Miles Prower.",
           "correct_answer": "True", "incorrect_answers": ["False"]},
          {"category": "Sports", "type": "boolean", "difficulty": "easy",
           "question": "Roger Federer is a famous soccer player.", "correct_answer": "False",
           "incorrect_answers": ["True"]},
          {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
           "question": "An Astronomical Unit is the distance between Earth and the Moon.",
           "correct_answer": "False", "incorrect_answers": ["True"]},
          {"category": "Sports", "type": "boolean", "difficulty": "medium",
           "question": "Formula E is an auto racing series that uses hybrid electric race cars.",
           "correct_answer": "False", "incorrect_answers": ["True"]},
          {"category": "Science & Nature", "type": "boolean", "difficulty": "hard",
           "question": "The chemical element Lithium is named after the country of Lithuania.",
           "correct_answer": "False", "incorrect_answers": ["True"]},
          {"category": "History", "type": "boolean", "difficulty": "hard",
           "question": "During the Winter War, the amount of Soviet Union soldiers"
                       " that died or went missing was five times more than Finland&#039;s.",
           "correct_answer": "True", "incorrect_answers": ["False"]},
          {"category": "Celebrities", "type": "boolean", "difficulty": "easy",
           "question": "Tupac Shakur died due to complications from being stabbed in 1996.",
           "correct_answer": "False", "incorrect_answers": ["True"]},
          {"category": "Mythology", "type": "boolean", "difficulty": "easy",
           "question": "A wyvern is the same as a dragon.", "correct_answer": "False",
           "incorrect_answers": ["True"]},
          {"category": "History", "type": "boolean", "difficulty": "easy",
           "question": "The United States of America was the first country to launch a man into space.",
           "correct_answer": "False", "incorrect_answers": ["True"]},
          {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
           "question": "The pickled gherkin was first added to hamburgers because a"
                       " US health law required all fast-food to include a source of Vitamin C.",
           "correct_answer": "False", "incorrect_answers": ["True"]},
          {"category": "Geography", "type": "boolean", "difficulty": "hard",
           "question": "Only one country in the world starts with the letter Q.",
           "correct_answer": "True", "incorrect_answers": ["False"]},
          {"category": "Geography", "type": "boolean", "difficulty": "medium",
           "question": "Is Tartu the capital of Estonia?", "correct_answer": "False",
           "incorrect_answers": ["True"]}

 ]


